### PR TITLE
Unitypackage

### PR DESCRIPTION
**Pull request by fraidev**
I needed to create a repo with a unity structure to respect our UPM structure. 
https://github.com/fraidev/tezos-unity-sdk-structured

I can transfer this repository to trilitech.

Proof that it's working on my fork:
https://github.com/fraidev/tezos-unity-sdk/releases/tag/2.0.3

### CODE REVIEW

**Comment by mismirnov** [comment]
@fraidev You must give the repo with unity structure to trilitech or we will create the repo ourselves.
Second choice is preferable but we can discuss this.

**Comment by fraidev** [comment]
> @fraidev You must give the repo with unity structure to trilitech or we will create the repo ourselves. Second choice is preferable but we can discuss this.

I already changed the to point to `trilitech/tezos-unity-sdk-structured`.
I don't have access to transfer the repo to trilitech.
You can fork it or create a new repo with the same name and add access to me to add the commits.

**Comment by mismirnov** [comment]
> > @fraidev You must give the repo with unity structure to trilitech or we will create the repo ourselves. Second choice is preferable but we can discuss this.
> 
> I already changed to point to `trilitech/tezos-unity-sdk-structured`. I don't have access to transfer the repo to trilitech. You can fork it or create a new repo with the same name and add access to me to add the commits.

I created project `trilitech/tezos-unity-sdk-structured`:
https://github.com/trilitech/tezos-unity-sdk-structured/
Invite has been sent.

**Comment by fraidev** [comment]
> https://github.com/trilitech/tezos-unity-sdk-structured/

Done!

**Review by mismirnov — APPROVED** [review]

**Pull request merged**
