### PR TITLE
Fix for missing dependency?

### PR DESCRIPTION
**Pull request by DevLaTron**
Should be:

using Newtonsoft.Json.Linq;

instead of

using Unity.Plastic.Newtonsoft.Json.Linq;

### CODE REVIEW

**Comment by DevLaTron** [comment]
Also added fix for Linux Editor

**Comment by cnbrk13** [comment]
Thank you for your contribution. If you prefer, you're welcome to submit a PR to the develop branch. Alternatively, I can incorporate your changes into the upcoming update that's currently in progress.

**Comment by DevLaTron** [comment]
Feel free to incorporate them manually, it's only a couple of lines. :)

**Comment by cnbrk13** [comment]
Will add manually.

**Pull request closed without merging**
